export enum CURRENCIES {
    USD = '$',
    INR = '₹',
    TWD = '$',
    HKD = '$',
    MYR = 'RM',
    AUD = '$',
    EUR = '€',
    GBP = '£',
    CAD = '$',
    ZAR = 'R',
    JPY = '¥',
    CHF = '₣',
    NZD = '$',
    CNY = '¥',
    SGD = '$',
    THB = '฿',
    PHP = '₱',
    IDR = 'Rp'
}